# This is a basic workflow to help you get started with Actions

name: flask

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : master base sha
      id : master_base_sha
      if : github.ref  == 'refs/heads/master'
      run: echo  "::set-output name=base_sha::${{ github.event.before }}"
    - uses: tayfun/flake8-your-pr@master
      with:
        secrets: ${{ secrets.GITHUB_TOKEN }}
